Admin button functionality
entur/entur-game-frontend pull request #50
Opened 2024-07-24 14:11 UTC by selmagudmundsen

## Pull Request Template

### PR Type 🍏

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] API
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] Documentation content changes
[ ] Tests
[ ] Other
```

[Kanban Link](https://www.notion.so/bekks/742fa46fd71e47728aff33e5a32e125e?v=4fe4766ee0f54d348a595b3864658662&p=a23b1e7a1a584a50a4848a9013f49ef6&pm=s)

### Context 🤷‍♀️
Updating the admin page from the MVP

### What's new? 👶
- Delete button on admin page deletes and removes card from the ladning page
- The "trekk vinner" and "avslutt spill" buttons have been moved into the Compact Leaderboard and has functionality according to that in the Figma model and with backend endpoints
- Alert boxes when there are no active events

### Screenshots 🖼️
![Screenshot 2024-07-24 at 15 58 35](https://github.com/user-attachments/assets/c4044bff-8e5b-4d55-b8ba-0bd8948ab8a7)
![Screenshot 2024-07-24 at 16 00 22](https://github.com/user-attachments/assets/7d53d220-1361-4210-be60-4f8ad5c3fa98)
![Screenshot 2024-07-24 at 16 00 30](https://github.com/user-attachments/assets/47a3b906-3a28-4ca2-b7a5-a882f143f348)

2024-07-24 14:34 UTC, maribsta requested changes
Noen av knappene fungerer ikke som de skal

2024-07-24 14:34 UTC, maribsta commented on src/lib/hooks/useScores.ts
> +// src/hooks/useScores.ts
Denne trengs ikke

2024-07-25 13:38 UTC, tomaswedege approved these changes
Megabra jobbet! Så lenge det å legge til Error Toasts blir lagt inn som et eget issue i boardet er det veldig godkjent fra min side😁🤩

2024-07-25 13:50 UTC, Magnus-Farstad requested changes
Very good!

2024-07-25 13:50 UTC, Magnus-Farstad commented on src/app/(white)/admin/leaderboard/[eventId]/page.tsx
>      }).isRequired,
Tror ikke dette er nødvendig når det er en Prop type EventPageProps

2024-07-25 13:50 UTC, Magnus-Farstad commented on src/app/(white)/admin/leaderboard/[eventId]/page.tsx
> -}: LeaderboardPageProps): JSX.Element => {
Hvis du bytter ut leaderboardprops med eventpageprops her, så skal eslint være good tror jeg

2024-07-25 13:52 UTC, selmagudmundsen commented on src/app/(white)/admin/leaderboard/[eventId]/page.tsx
> -}: LeaderboardPageProps): JSX.Element => {
fiksa

2024-07-25 13:54 UTC, merged